spring.application.name=stock-management
server.port=8081

# ============================================
#               POSTGRESQL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db-name
spring.datasource.username=username
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev