spring.application.name=stock-management
server.port=8081



# ============================================
# JWT & TIMEZONE
# ============================================
jwt.token.secret=U3VwZXIvU2VjcmV0LXN0cmluZ0B2YWxpZGF0aW9uLmtleS11c2VkLXRvLWVuY29kZS1qd3Rz
jwt.token.expire-in-ms=86400000
zone=Africa/Algiers
# ============================================
#               POSTGRESQL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db-name
spring.datasource.username=username
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev