spring.application.name=stock-management-dev
server.port=8081
# ============================================
#               POSTGRESQL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/stock-db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# JWT & TIMEZONE
# ============================================
jwt.token.secret=U3VwZXIvU2VjcmV0LXN0cmluZ0B2YWxpZGF0aW9uLmtleS11c2VkLXRvLWVuY29kZS1qd3Rz
jwt.token.expire-in-ms=86400000
zone=Africa/Algiers
